object frmEntrada: TfrmEntrada
  Left = 0
  Top = 0
  Caption = 'Entrada'
  ClientHeight = 437
  ClientWidth = 896
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poDesktopCenter
  OnActivate = FormActivate
  PixelsPerInch = 96
  TextHeight = 13
  object PaintBox1: TPaintBox
    Left = 0
    Top = 0
    Width = 896
    Height = 437
    Align = alClient
    OnPaint = PaintBox1Paint
    ExplicitLeft = 496
    ExplicitTop = 192
    ExplicitWidth = 105
    ExplicitHeight = 105
  end
end
